site_name: Sightline Docs

# Remove these two to go back to no languages.
docs_dir: '../../docs/en'
site_dir: '../../generated/en'

theme:
  name: material
  custom_dir: '../../overrides/'
  favicon: assets/images/favicon.ico
  logo: assets/images/Sightline_SL_Blue.png
  language: en
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle: 
        icon: material/brightness-7
        name: Switch to dark mode
      

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle: 
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Montserrat

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - toc.follow
    - navigation.top

extra_css:
  - assets/stylesheets/main.min.css
  - assets/stylesheets/palette.min.css

# Remove this extra section to go back to no languages.
extra:
  alternate:

    # English
    - name: English
      link: /en/ 
      lang: en

    # Spanish
    - name: Espa√±ol
      link: /es/
      lang: es

plugins:
  - search:
      lang: en

#nav:
# - Home: index.md
# - Basics: Basics/
# - Setup: Initial Setup/0 Welcome.md
# - Plans: Plans/0 | Welcome.md
